import React, { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { jsPDF } from 'jspdf'
import { supabase } from '../lib/supabase'
import { createPdfExportContext, formatUtcDateTime, getCurrentActorProfile, isAuditSuperadminEmail } from '../lib/compliance'
import { confirmEvidencePdfExport } from '../lib/exportAttestation.jsx'
import './SystemRecords.css'

const SYSTEM_RECORDS_LIMIT = 100000
const SYSTEM_RECORDS_PAGE_SIZE = 1000
const PDF_MARGIN = 14

const previewJson = (value, maxLength = 500) => {
  const text = JSON.stringify(value || {}, null, 2)
  return text.length > maxLength ? `${text.slice(0, maxLength)}...` : text
}

const sanitizeFilePart = (value) => String(value || '')
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/^-+|-+$/g, '')

const buildPdfFilename = (activeView, entityFilter) => {
  const datePart = new Date().toISOString().slice(0, 10)
  const viewPart = sanitizeFilePart(activeView)
  const filterPart = sanitizeFilePart(entityFilter === 'all' ? 'all-entities' : entityFilter)
  return `system-records-${viewPart}-${filterPart}-${datePart}.pdf`
}

const drawPdfFooter = (doc, exportMeta) => {
  const pageHeight = doc.internal.pageSize.getHeight()
  const pageWidth = doc.internal.pageSize.getWidth()

  doc.setDrawColor(229, 229, 229)
  doc.line(PDF_MARGIN, pageHeight - 18, pageWidth - PDF_MARGIN, pageHeight - 18)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(107, 114, 128)
  doc.text(`Exported ${exportMeta.generatedAtLabel}`, pageWidth - PDF_MARGIN, pageHeight - 13, { align: 'right' })

  doc.setFontSize(6)
  doc.text('This export reflects filtered system records visible to the authorized superadmin at the time of retrieval.', PDF_MARGIN, pageHeight - 9)
  doc.text(`Print UUID: ${exportMeta.exportId}`, pageWidth / 2, pageHeight - 5, { align: 'center' })
}

const drawPdfHeader = ({ doc, activeView, exportMeta, recordCount, entityFilter, searchTerm, pageNumber }) => {
  const pageWidth = doc.internal.pageSize.getWidth()
  const title = activeView === 'events' ? 'System Records - Audit Events' : 'System Records - Record History'
  const filterLabel = entityFilter === 'all' ? 'All entities' : (ENTITY_LABELS[entityFilter] || entityFilter)
  let y = PDF_MARGIN

  if (pageNumber === 1) {
    doc.setFillColor(23, 23, 23)
    doc.rect(0, 0, pageWidth, 28, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(17)
    doc.text(title, PDF_MARGIN, 12)
    doc.setFontSize(9)
    doc.setTextColor(209, 213, 219)
    doc.text(`Filtered export · ${recordCount} records`, PDF_MARGIN, 18)

    y = 36
    doc.setDrawColor(229, 229, 229)
    doc.setFillColor(250, 250, 250)
    doc.roundedRect(PDF_MARGIN, y, pageWidth - PDF_MARGIN * 2, 22, 2, 2, 'FD')
    doc.setTextColor(107, 114, 128)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.text('GENERATED BY', PDF_MARGIN + 4, y + 6)
    doc.text('DATA RETRIEVED', PDF_MARGIN + 72, y + 6)
    doc.text('ENTITY FILTER', PDF_MARGIN + 140, y + 6)
    doc.text('SEARCH', PDF_MARGIN + 4, y + 15)
    doc.setTextColor(23, 23, 23)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.text(exportMeta.generatedByLabel, PDF_MARGIN + 4, y + 11)
    doc.text(exportMeta.generatedAtLabel, PDF_MARGIN + 72, y + 11)
    doc.text(filterLabel, PDF_MARGIN + 140, y + 11)
    const searchPreview = searchTerm?.trim() ? searchTerm.trim() : 'No search filter'
    doc.text(doc.splitTextToSize(searchPreview, pageWidth - PDF_MARGIN * 2 - 8), PDF_MARGIN + 4, y + 19)
    y += 30
  } else {
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(23, 23, 23)
    doc.setFontSize(12)
    doc.text(title, PDF_MARGIN, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(107, 114, 128)
    doc.text(`Page ${pageNumber}`, pageWidth - PDF_MARGIN, y, { align: 'right' })
    y += 8
  }

  return y
}

const renderSystemRecordsPdf = async ({
  activeView,
  items,
  entityFilter,
  searchTerm,
  checklistNames,
}) => {
  const confirmed = await confirmEvidencePdfExport({
    title: 'This export contains audit evidence and system record history.',
    details: `${items.length} record${items.length === 1 ? '' : 's'} · ${activeView === 'events' ? 'Audit Events' : 'Record History'}`,
  })
  if (!confirmed) return false

  const filename = buildPdfFilename(activeView, entityFilter)
  const exportMeta = await createPdfExportContext({
    eventType: activeView === 'events' ? 'pdf_export.system_records.audit_events' : 'pdf_export.system_records.history',
    fileName: filename,
    tableName: activeView === 'events' ? 'audit_events' : null,
    metadata: {
      view: activeView,
      entity_filter: entityFilter,
      search_term: searchTerm?.trim() || null,
      record_count: items.length,
    },
  })

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const contentWidth = pageWidth - PDF_MARGIN * 2
  let pageNumber = 1
  let y = drawPdfHeader({ doc, activeView, exportMeta, recordCount: items.length, entityFilter, searchTerm, pageNumber })

  const ensureSpace = (requiredHeight) => {
    if (y + requiredHeight <= pageHeight - 24) return
    drawPdfFooter(doc, exportMeta)
    doc.addPage()
    pageNumber += 1
    y = drawPdfHeader({ doc, activeView, exportMeta, recordCount: items.length, entityFilter, searchTerm, pageNumber })
  }

  items.forEach((item, index) => {
    const summary = activeView === 'events'
      ? summarizeAuditEvent(item)
      : summarizeHistoryRecord(item, checklistNames)

    const metaLine = activeView === 'events'
      ? [
          item.event_type,
          ENTITY_LABELS[item.table_name || (item.event_type?.startsWith('admin_') ? 'admin' : 'system')] || item.table_name || 'System',
          item.actor_email || 'Unknown actor',
          formatUtcDateTime(item.created_at),
          item.record_id ? `Record ${item.record_id}` : 'No record id',
        ].join(' | ')
      : [
          item.entityLabel,
          `${item.operation} v${item.version_no}`,
          item.changed_by_email || 'Unknown actor',
          formatUtcDateTime(item.changed_at),
          `Record ${item.record_id}`,
        ].join(' | ')

    const detailsLine = activeView === 'events'
      ? previewJson(item.metadata)
      : `Before: ${previewJson(item.row_before, 220)}\nAfter: ${previewJson(item.row_after, 220)}`

    const summaryLines = doc.splitTextToSize(`${index + 1}. ${summary}`, contentWidth)
    const metaLines = doc.splitTextToSize(metaLine, contentWidth)
    const detailsLines = doc.splitTextToSize(detailsLine, contentWidth)
    const blockHeight = (summaryLines.length * 5) + (metaLines.length * 4) + (detailsLines.length * 3.5) + 9

    ensureSpace(blockHeight)

    doc.setDrawColor(229, 229, 229)
    doc.line(PDF_MARGIN, y, pageWidth - PDF_MARGIN, y)
    y += 4

    doc.setFont('helvetica', 'bold')
    doc.setTextColor(23, 23, 23)
    doc.setFontSize(10)
    doc.text(summaryLines, PDF_MARGIN, y)
    y += summaryLines.length * 5

    doc.setFont('helvetica', 'normal')
    doc.setTextColor(90, 99, 110)
    doc.setFontSize(8)
    doc.text(metaLines, PDF_MARGIN, y)
    y += metaLines.length * 4 + 1

    doc.setTextColor(55, 65, 81)
    doc.setFontSize(7)
    doc.text(detailsLines, PDF_MARGIN, y)
    y += detailsLines.length * 3.5 + 4
  })

  drawPdfFooter(doc, exportMeta)
  doc.save(filename)
  return true
}

const fetchLimitedRows = async (queryFactory, limit) => {
  const rows = []
  let from = 0

  while (rows.length < limit) {
    const remaining = limit - rows.length
    const pageSize = Math.min(SYSTEM_RECORDS_PAGE_SIZE, remaining)
    const { data, error } = await queryFactory().range(from, from + pageSize - 1)

    if (error) throw error
    if (!data || data.length === 0) break

    rows.push(...data)

    if (data.length < pageSize) break
    from += pageSize
  }

  return rows
}

const ENTITY_LABELS = {
  meetings: 'Toolbox Meetings',
  incidents: 'Incidents',
  corrective_actions: 'Corrective Actions',
  checklist_completions: 'Checklist Completions',
  admin: 'Admin Operations',
  system: 'System',
}

const HISTORY_SOURCES = [
  {
    key: 'meetings',
    label: 'Toolbox Meetings',
    table: 'meeting_history',
    idColumn: 'meeting_id',
  },
  {
    key: 'incidents',
    label: 'Incidents',
    table: 'incident_history',
    idColumn: 'incident_id',
  },
  {
    key: 'corrective_actions',
    label: 'Corrective Actions',
    table: 'corrective_action_history',
    idColumn: 'corrective_action_id',
  },
  {
    key: 'checklist_completions',
    label: 'Checklist Completions',
    table: 'checklist_completion_history',
    idColumn: 'checklist_completion_id',
  },
]

const shortId = (value) => String(value || '').slice(0, 8)

const summarizeAuditEvent = (event) => {
  const metadata = event.metadata || {}

  if (event.event_type?.startsWith('pdf_export.')) {
    return metadata.file_name || 'PDF export'
  }

  if (event.table_name === 'meetings') {
    return metadata.topic || 'Meeting record'
  }

  if (event.table_name === 'incidents') {
    return [metadata.type_name, metadata.employee_name].filter(Boolean).join(' - ') || 'Incident record'
  }

  if (event.table_name === 'corrective_actions') {
    return metadata.description || 'Corrective action record'
  }

  if (event.table_name === 'checklist_completions') {
    return metadata.signer_name || metadata.completion_datetime || 'Checklist completion record'
  }

  if (event.table_name === 'users') {
    return metadata.target_email || metadata.user_email || 'User administration event'
  }

  return metadata.file_name || event.event_type || 'System event'
}

const summarizeHistoryRecord = (entry, checklistNames) => {
  const snapshot = entry.row_after || entry.row_before || {}

  if (entry.entity === 'meetings') {
    return snapshot.topic || 'Toolbox meeting'
  }

  if (entry.entity === 'incidents') {
    return [snapshot.type_name, snapshot.employee_name].filter(Boolean).join(' - ') || 'Incident'
  }

  if (entry.entity === 'corrective_actions') {
    return snapshot.description || 'Corrective action'
  }

  if (entry.entity === 'checklist_completions') {
    const checklistName = checklistNames.get(snapshot.checklist_id) || ''
    return [checklistName, snapshot.signer_name].filter(Boolean).join(' - ') || 'Checklist completion'
  }

  return 'Record history'
}

const formatJson = (value) => JSON.stringify(value || {}, null, 2)

export default function SystemRecords() {
  const navigate = useNavigate()
  const [authChecked, setAuthChecked] = useState(false)
  const [loading, setLoading] = useState(true)
  const [activeView, setActiveView] = useState('events')
  const [events, setEvents] = useState([])
  const [historyEntries, setHistoryEntries] = useState([])
  const [checklistNames, setChecklistNames] = useState(new Map())
  const [searchTerm, setSearchTerm] = useState('')
  const [entityFilter, setEntityFilter] = useState('all')
  const [errorMessage, setErrorMessage] = useState('')
  const [exportingPdf, setExportingPdf] = useState(false)

  useEffect(() => {
    const bootstrap = async () => {
      const actor = await getCurrentActorProfile()
      const allowed = isAuditSuperadminEmail(actor.email)
      setAuthChecked(true)

      if (!allowed) {
        navigate('/', { replace: true })
        return
      }

      await fetchRecords()
    }

    bootstrap()
  }, [navigate])

  const fetchRecords = async () => {
    setLoading(true)
    setErrorMessage('')

    let eventsRes
    let historyRes

    try {
      ;[eventsRes, ...historyRes] = await Promise.all([
      fetchLimitedRows(() => (
        supabase
          .from('audit_events')
          .select('*')
          .order('created_at', { ascending: false })
      ), SYSTEM_RECORDS_LIMIT),
      ...HISTORY_SOURCES.map((source) =>
        fetchLimitedRows(() => (
          supabase
            .from(source.table)
            .select('*')
            .order('changed_at', { ascending: false })
        ), SYSTEM_RECORDS_LIMIT)
      ),
    ])
    } catch (error) {
      setErrorMessage(error.message || 'Unable to load system records.')
      setLoading(false)
      return
    }

    const normalizedHistory = HISTORY_SOURCES.flatMap((source, index) => {
      const rows = historyRes[index] || []
      return rows.map((row) => ({
        ...row,
        entity: source.key,
        entityLabel: source.label,
        record_id: row[source.idColumn],
      }))
    }).sort((left, right) => new Date(right.changed_at) - new Date(left.changed_at))

    const checklistIds = [...new Set(normalizedHistory
      .filter((entry) => entry.entity === 'checklist_completions')
      .flatMap((entry) => [entry.row_after?.checklist_id, entry.row_before?.checklist_id])
      .filter(Boolean))]

    if (checklistIds.length > 0) {
      const { data: checklistsData } = await supabase
        .from('checklists')
        .select('id, name')
        .in('id', checklistIds)

      setChecklistNames(new Map((checklistsData || []).map((item) => [item.id, item.name])))
    } else {
      setChecklistNames(new Map())
    }

    setEvents(eventsRes)
    setHistoryEntries(normalizedHistory)
    setLoading(false)
  }

  const filteredEvents = useMemo(() => {
    const query = searchTerm.trim().toLowerCase()

    return events.filter((event) => {
      const derivedEntity = event.table_name || (event.event_type?.startsWith('admin_') ? 'admin' : 'system')
      const haystack = [
        event.event_type,
        event.table_name,
        event.actor_email,
        event.record_id,
        summarizeAuditEvent(event),
        formatJson(event.metadata),
      ].join(' ').toLowerCase()

      const matchesEntity = entityFilter === 'all' || derivedEntity === entityFilter
      const matchesQuery = !query || haystack.includes(query)
      return matchesEntity && matchesQuery
    })
  }, [entityFilter, events, searchTerm])

  const filteredHistory = useMemo(() => {
    const query = searchTerm.trim().toLowerCase()

    return historyEntries.filter((entry) => {
      const haystack = [
        entry.entity,
        entry.changed_by_email,
        entry.record_id,
        summarizeHistoryRecord(entry, checklistNames),
        formatJson(entry.row_before),
        formatJson(entry.row_after),
      ].join(' ').toLowerCase()

      const matchesEntity = entityFilter === 'all' || entry.entity === entityFilter
      const matchesQuery = !query || haystack.includes(query)
      return matchesEntity && matchesQuery
    })
  }, [checklistNames, entityFilter, historyEntries, searchTerm])

  if (!authChecked || loading) {
    return <div className="spinner"></div>
  }

  const activeItems = activeView === 'events' ? filteredEvents : filteredHistory

  const handleExportPdf = async () => {
    if (activeItems.length === 0) return

    setExportingPdf(true)
    try {
      const exported = await renderSystemRecordsPdf({
        activeView,
        items: activeItems,
        entityFilter,
        searchTerm,
        checklistNames,
      })
      if (!exported) return
    } catch (error) {
      console.error('System records PDF export failed:', error)
      setErrorMessage(error.message || 'Unable to export PDF.')
    } finally {
      setExportingPdf(false)
    }
  }

  return (
    <div className="system-records-page">
      <div className="page-header system-records-header">
        <div>
          <h1>System Records</h1>
          <p className="system-records-subtitle">
            Hidden superadmin trace for audit events and record history snapshots.
          </p>
        </div>
        <div className="system-records-actions">
          <button className="btn btn-secondary" onClick={handleExportPdf} disabled={exportingPdf || activeItems.length === 0}>
            {exportingPdf ? 'Generating PDF...' : 'Export PDF'}
          </button>
          <button className="btn btn-secondary" onClick={fetchRecords}>Refresh</button>
          <button className="btn btn-secondary" onClick={() => navigate('/')}>Back</button>
        </div>
      </div>

      <div className="system-records-summary">
        <div className="system-records-stat card">
          <span className="system-records-stat-label">Audit Events</span>
          <strong>{events.length}</strong>
          <span className="system-records-stat-note">Up to 100000 records</span>
        </div>
        <div className="system-records-stat card">
          <span className="system-records-stat-label">History Snapshots</span>
          <strong>{historyEntries.length}</strong>
          <span className="system-records-stat-note">Up to 100000 per tracked entity</span>
        </div>
        <div className="system-records-stat card">
          <span className="system-records-stat-label">Visible Result Set</span>
          <strong>{activeItems.length}</strong>
          <span className="system-records-stat-note">After filters</span>
        </div>
      </div>

      <div className="card system-records-toolbar">
        <div className="system-records-tabs">
          <button
            className={`system-records-tab${activeView === 'events' ? ' is-active' : ''}`}
            onClick={() => setActiveView('events')}
          >
            Audit Events
          </button>
          <button
            className={`system-records-tab${activeView === 'history' ? ' is-active' : ''}`}
            onClick={() => setActiveView('history')}
          >
            Record History
          </button>
        </div>

        <div className="system-records-filters">
          <input
            type="text"
            className="filter-search-input"
            placeholder="Search event type, email, record id, JSON..."
            value={searchTerm}
            onChange={(event) => setSearchTerm(event.target.value)}
          />
          <select
            className="filter-select"
            value={entityFilter}
            onChange={(event) => setEntityFilter(event.target.value)}
          >
            <option value="all">All entities</option>
            <option value="meetings">Toolbox Meetings</option>
            <option value="incidents">Incidents</option>
            <option value="corrective_actions">Corrective Actions</option>
            <option value="checklist_completions">Checklist Completions</option>
            <option value="admin">Admin Operations</option>
            <option value="system">System</option>
          </select>
        </div>
      </div>

      {errorMessage && (
        <div className="card system-records-error">{errorMessage}</div>
      )}

      <div className="system-records-list">
        {activeItems.length === 0 ? (
          <div className="card system-records-empty">No records match the current filters.</div>
        ) : activeView === 'events' ? (
          filteredEvents.map((event) => {
            const entityKey = event.table_name || (event.event_type?.startsWith('admin_') ? 'admin' : 'system')
            return (
              <article key={event.id} className="card system-record-card">
                <div className="system-record-card-topline">
                  <span className="system-record-badge">{ENTITY_LABELS[entityKey] || entityKey}</span>
                  <span className="system-record-type">{event.event_type}</span>
                </div>
                <h3>{summarizeAuditEvent(event)}</h3>
                <div className="system-record-meta-grid">
                  <div>
                    <span className="system-record-meta-label">UTC</span>
                    <strong>{formatUtcDateTime(event.created_at)}</strong>
                  </div>
                  <div>
                    <span className="system-record-meta-label">Actor</span>
                    <strong>{event.actor_email || 'Unknown actor'}</strong>
                  </div>
                  <div>
                    <span className="system-record-meta-label">Record</span>
                    <strong>{event.record_id ? shortId(event.record_id) : 'n/a'}</strong>
                  </div>
                </div>
                <details className="system-record-details">
                  <summary>Metadata</summary>
                  <pre>{formatJson(event.metadata)}</pre>
                </details>
              </article>
            )
          })
        ) : (
          filteredHistory.map((entry) => (
            <article key={entry.id} className="card system-record-card">
              <div className="system-record-card-topline">
                <span className="system-record-badge">{entry.entityLabel}</span>
                <span className={`system-record-type operation-${entry.operation?.toLowerCase()}`}>{entry.operation}</span>
              </div>
              <h3>{summarizeHistoryRecord(entry, checklistNames)}</h3>
              <div className="system-record-meta-grid">
                <div>
                  <span className="system-record-meta-label">UTC</span>
                  <strong>{formatUtcDateTime(entry.changed_at)}</strong>
                </div>
                <div>
                  <span className="system-record-meta-label">Actor</span>
                  <strong>{entry.changed_by_email || 'Unknown actor'}</strong>
                </div>
                <div>
                  <span className="system-record-meta-label">Version</span>
                  <strong>v{entry.version_no}</strong>
                </div>
                <div>
                  <span className="system-record-meta-label">Record</span>
                  <strong>{shortId(entry.record_id)}</strong>
                </div>
              </div>
              <details className="system-record-details">
                <summary>Before</summary>
                <pre>{formatJson(entry.row_before)}</pre>
              </details>
              <details className="system-record-details">
                <summary>After</summary>
                <pre>{formatJson(entry.row_after)}</pre>
              </details>
            </article>
          ))
        )}
      </div>
    </div>
  )
}