-- Add High Wind Roofing Operations safety topic
INSERT INTO safety_topics (name, category, osha_reference, description, risk_level)
SELECT
  'High Wind Roofing Operations',
  'Weather & Environmental Hazards',
  'OSHA 29 CFR 1926.502',
  'Wind is an invisible and dynamic hazard that can change conditions on a roof faster than workers can react. Unlike most job site hazards that remain static once identified, wind escalates without warning. A roof that is safe to work on at 15 mph can become lethal at 35 mph. Every roofing operation must include a defined wind threshold, a monitoring plan, and a clear stop-work trigger before the first worker steps onto the roof.

• Pre-Shift Wind Assessment
Current wind speed and gusts must be measured before work begins — visual estimation is not sufficient. The wind forecast must be reviewed for the entire planned shift, not just the morning conditions. The company wind threshold for roofing operations must be verified and confirmed before proceeding. Any continuation of work under elevated wind conditions must be explicitly authorized by the supervisor, with the specific conditions documented.

• Fall Protection Integrity in Wind
Wind loads impose lateral forces on workers and fall protection systems. Fall protection equipment must be inspected and all connections verified before work begins. Lifelines must be properly tensioned and positioned to reduce swing fall hazard — wind can push a worker laterally during a fall, increasing the arc and the risk of striking an obstruction. Warning lines must be checked for stability in gusts; a warning line system that moves or sags in wind no longer provides reliable hazard demarcation. Guardrails must be inspected for secure anchoring at each post — wind uplift forces on guardrail panels can exceed design loads in high wind events.

• Access and Scaffold Stability
Ladders must be tied off at the top and secured at the base before climbing and must remain secured throughout the shift — wind can shift a ladder that appeared stable before conditions changed. Scaffold ties and bracing must be inspected before the shift begins; scaffold systems are designed for specific wind load assumptions and must be properly tied to the structure to maintain stability. The roof access point must be evaluated for wind exposure — certain building shapes and roof configurations create wind acceleration zones at access points.

• Material Control
Lightweight roofing materials represent one of the most significant wind hazards on a roof. Shingles, underlayment, membrane rolls, and insulation boards must be weighted or fastened immediately upon staging — never left loose. Loose insulation boards must be secured the moment they are placed. Tarps must be properly fastened at all edges and intermediate points; an improperly secured tarp in wind generates enormous uplift forces that can pull anchor points, overturn staging, and create a projectile hazard. If wind increases beyond the tarp''s secure attachment capacity, the tarp must be removed rather than left in place. Tools must be tethered where appropriate. Buckets, containers, and lightweight equipment must be secured against displacement. Debris must be removed promptly throughout the shift to prevent wind-driven lift-off of scrap material.

• Lifting and Hoisting Operations
Hoisting operations must be paused during strong gusts — wind loading on materials being lifted creates unpredictable forces on the rigging, the structure, and the workers guiding the load. Tag lines must be used for all material lifting to maintain directional control and prevent the load from swinging into workers or the structure.

• Worker Movement and Positioning
Workers must maintain a low center of gravity when moving on a slope in elevated wind conditions — gusts can cause sudden loss of balance, particularly when carrying material. No worker should perform tasks at or near the roof edge during extreme gusts; work near the perimeter must be suspended until conditions stabilize. Workers must communicate continuously with each other during high-wind operations — the noise generated by wind can mask calls for help, tool drops, and material displacement sounds.

• Monitoring and Storm Awareness
Weather radar must be monitored for approaching storm cells throughout the shift — surface wind conditions can change dramatically as a storm approaches. The ground drop zone must be controlled and barricaded during high-wind operations, as wind-driven debris and displaced materials can travel significant distances.

• Stop-Work Authority
Stop-work authority must be reinforced with every crew member before high-wind operations begin. The wind threshold must be explicitly communicated — not implied. Work must be suspended immediately if materials begin to displace on the roof surface; displaced materials are an indicator that wind conditions have exceeded the safe operating envelope, regardless of the measured wind speed. Any worker who observes conditions exceeding the threshold or sees materials displacing must stop work and notify the supervisor without waiting to be told.

Remember: Wind does not negotiate. It does not give a warning before it knocks a worker off a roof or sends a sheet of insulation into someone on the ground. Set the threshold before the shift, monitor continuously, and stop the moment conditions exceed it.',
  'critical'
WHERE NOT EXISTS (
  SELECT 1 FROM safety_topics WHERE name = 'High Wind Roofing Operations'
);
